services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite

    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
      --skipApiVersionCheck
      --location /data

    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

    volumes:
      - azurite_data:/data

  appfunction:
    build:
      context: ../src/AppFunction
      dockerfile: Dockerfile
    container_name: appfunction
    depends_on:
      - azurite
    environment:
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      AzureWebJobsStorage: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      ConnectionStrings__Storage: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://localhost/
    ports:
      - "7071:80"

  logworkermaker:
    build:
      context: ../src/worker/LogWorkerMaker
      dockerfile: Dockerfile
    container_name: logworkermaker
    depends_on:
      - azurite
    environment:
      ConnectionStrings__Storage: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;

  web:
    build:
      context: ../src/web
      dockerfile: Dockerfile
    container_name: logsviewer-web
    ports:
      - "5173:5173"
    environment:
      VITE_DEMO_USER: demo
      VITE_DEMO_PASSWORD: demo123
      VITE_API_BASE_URL: /api
      VITE_PROXY_TARGET: http://appfunction:80
      VITE_LOGS_REFRESH_MS: 5000
    depends_on:
      - appfunction

volumes:
  azurite_data: